apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qe-ingress
  namespace: quantum-edge
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/group.name: quantum-edge
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: qe-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qe-dashboard
                port:
                  number: 80
