#!/usr/bin/env python3
"""Interactive setup script for Quantum Edge JWT authentication.

Prompts for an admin password, generates a bcrypt hash and JWT secret,
and appends the values to .env.
"""

import getpass
import secrets
import sys
from pathlib import Path

import bcrypt


def main() -> None:
    env_path = Path(__file__).resolve().parent.parent / ".env"

    print("╔══════════════════════════════════════╗")
    print("║  Quantum Edge — Auth Setup           ║")
    print("╚══════════════════════════════════════╝\n")

    username = input("Admin username [admin]: ").strip() or "admin"

    password = getpass.getpass("Admin password: ")
    if not password:
        print("Error: password cannot be empty.")
        sys.exit(1)

    confirm = getpass.getpass("Confirm password: ")
    if password != confirm:
        print("Error: passwords do not match.")
        sys.exit(1)

    password_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
    jwt_secret = secrets.token_hex(32)

    lines = [
        "",
        "# ─── Auth (generated by setup_auth.py) ───",
        f"QE_ADMIN_USERNAME={username}",
        f"QE_ADMIN_PASSWORD_HASH={password_hash}",
        f"QE_JWT_SECRET={jwt_secret}",
        "QE_JWT_EXPIRE_HOURS=24",
        "",
    ]

    with open(env_path, "a") as f:
        f.write("\n".join(lines))

    print(f"\nAuth credentials written to {env_path}")
    print(f"  Username: {username}")
    print(f"  JWT secret: {jwt_secret[:8]}...{jwt_secret[-8:]}")
    print("\nRestart the API to apply changes.")


if __name__ == "__main__":
    main()
